### ISSUE TITLE
input_calibration

### ISSUE THREAD

**Issue by daniel89710** [AlexeyAB/yolo2_light#10]
I want to quantize custom yolov3.
Could you introduce how to get input_calibration?

**Comment by AlexeyAB** [comment]
Run command:
`./darknet detector calibrate data/obj.data yolo-obj.cfg yolo-obj_2700.weights -input_calibration 100`
will be created file `input_calibration.txt`

in the `obj.data` file should be parameter `valid = data/train.txt` where is file `train.txt` contains list of 100 images.

**Comment by daniel89710** [comment]
Thank you for your information.
I will try that.

By the way, can we run 8bit quantized yolov3 on Tensor Core?

**Comment by AlexeyAB** [comment]
@daniel89710 

I think yes. Update your code from GitHub, I just added these lines: https://github.com/AlexeyAB/yolo2_light/blob/d93979f51e3e54a223fc4e1a1d6a0b1947aa263a/src/additionally.c#L1684-L1686

On Volta/Turing architectures, for example on RTX 2080Ti, INT8 (`215 Tflosp`) is **2x-4x times faster** than Tensor-Cores(FP16/FP16 `107 Tflops` - FP16/FP32 `26 Tflops`), so I think INT8 is processed on Tensor Cores too.

----

![tesla_05](https://user-images.githubusercontent.com/4096485/46906117-20fd6c00-cf07-11e8-90e3-b26b8c1af9a9.png)

----

![comparison-1](https://user-images.githubusercontent.com/4096485/46906119-25c22000-cf07-11e8-8e8f-224d06656376.jpg)

**Comment by daniel89710** [comment]
That's awesome!
Thank you very much.
I'll try.

**Comment by AlexeyAB** [comment]
It seems that INT8 on Tensor Cores is supported **only for CC 7.2**: Jetson Xavier, DRIVE PX Xavier/Pegasus
with Xavier SoC.
And it isn't supported for Tesla V100 (**CC 7.0**) and GeForce RTX 2080 Ti - 2070 (**CC 7.5**).

https://docs.nvidia.com/deeplearning/sdk/cudnn-developer-guide/index.html#tensor-ops-speedup-tips

> Note: Note that this CUDNN_DATA_INT8x32 is only supported by sm_72.

About it: https://github.com/AlexeyAB/yolo2_light/issues/18#issuecomment-431380610

**Comment by reethimalisetty** [comment]
Sir, I have used yolo v3 for detection of faces in image. I have four classes . For my test mAP I got 98.41. I test for 56 images and got 48 images detected correctly with their respective class. The problem is how to make confusion matrix from it. Please help me

**Comment by aluds123** [comment]
> Run command:
> `./darknet detector calibrate data/obj.data yolo-obj.cfg yolo-obj_2700.weights -input_calibration 100`
> will be created file `input_calibration.txt`
> 
> in the `obj.data` file should be parameter `valid = data/train.txt` where is file `train.txt` contains list of 100 images.



But it shows "there isn't such command" 
Could you tell me what's problem ?
