### ISSUE TITLE
low precision on INT8 inference CPU version

### ISSUE THREAD

**Issue by YL-123** [AlexeyAB/yolo2_light#21]
Hi, I used a custom face detector and test both float 32 and INT 8 inference on a single image,
here is my test result with how many faces detected and the speed when tested.

CPU+ Float32 inference: 749 faces, 61.839 s
GPU+ Float32 inference: 749 faces, 0.139 s
CPU+ INT 8 inference: 2 faces, 33.402 s
GPU+ INT 8 inference: 492 faces, 0.112 s

I can see that the GPU version is much faster than CPU, and Float 32 inference is slower than INT 8 inference which is expected. It is strange to me that the CPU + INT8 only detected 2 faces, which is much less than GPU + INT8. Any ideas what's going on here? thanks

**Comment by AlexeyAB** [comment]
@Yinling-123 Hi,

* What params did you use in Makefile for CPU+INT8?

* What mAP can you get for CPU+INT8 and GPU+INT8?
`./darknet detector map data/obj.data yolo_obj.cfg yolo_obj.weights -thresh 0.15`

**Comment by Yinling-123** [comment]
Following are some warnings from the output when did the INT 8 inference. 

Quantinization! 
 old_weight_mult = 4.000000, weights_multiplier_single = 4.000000 

 Warning: input_calibration= in the cfg-file has less values 0 than convolutional layers 0 
 Multiplers: weights 4, input 40, output 8 
 old_weight_mult = 256.000000, weights_multiplier_single = 256.000000 

 Warning: input_calibration= in the cfg-file has less values 0 than convolutional layers 1 
 Multiplers: weights 256, input 40, output 0.125 
 old_weight_mult = 64.000000, weights_multiplier_single = 64.000000 

 Warning: input_calibration= in the cfg-file has less values 0 than convolutional layers 2 
 Multiplers: weights 64, input 40, output 0.5 
 old_weight_mult = 256.000000, weights_multiplier_single = 256.000000

**Comment by Yinling-123** [comment]
GPU=0
OPENCV=0
OPENMP=0
AVX=0
SSE=0
all 0s in the Makefile for CPU+INT8 and CPU+ Float32, I am running the ./darknet detector map data/obj.data yolo_obj.cfg yolo_obj.weights -thresh 0.15

**Comment by AlexeyAB** [comment]
> Following are some warnings from the output when did the INT 8 inference.

* Did you add parameter `input_calibration=` to your cfg file?
* Can you rename your cfg-file to the txt-file and attach it to your message?
* Also try to use `OPENMP=1 SSE=1` or `OPENMP=1 AVX=1`

https://github.com/AlexeyAB/yolo2_light#yolo2_light

> How to use INT8-inference:
> 
> * Use flag -quantized at the end of command, for example, tiny-yolo-int8.sh or yolo_cpu_int8.cmd
> * **For the custom dataset, you should use input_calibration= parameter in your cfg-file, from the correspon cfg-file: yolov3-tiny.cfg or yolov3.cfg, ...**

**Comment by Yinling-123** [comment]
Here is output for GPU+INT8:
./darknet detector map obj.data obj.cfg face.backup -thresh 0.15 -quantized

detections_count = 808240, unique_truth_count = 194506  
class_id = 0, name = face, 08240 ap = 70.47 % 
 for thresh = 0.15, precision = 0.79, recall = 0.66, F1-score = 0.72 
 for thresh = 0.15, TP = 129314, FP = 34161, FN = 65192, average IoU = 59.00 % 
 mean average precision (mAP) = 0.704719, or 70.47 % 
Total Detection Time: 2603.000000 Seconds

**Comment by Yinling-123** [comment]
Did you add parameter input_calibration= to your cfg file?
    Yes, I add input_calibration= just before the 1st convolutional layer in cfg.
Can you rename your cfg-file to the txt-file and attach it to your message?
     See attached
Also try to use OPENMP=1 SSE=1 or OPENMP=1 AVX=1
 --Wow, it works!
OPENMP=1 SSE=1 CPU+ INT 8 inference: 492 faces, 0.106 s
OPENMP=1 AVX=1 CPU+ INT 8 inference: 492 faces, 0.106 s
[test.txt](https://github.com/AlexeyAB/yolo2_light/files/2503795/test.txt)

Thanks!

**Comment by Yinling-123** [comment]
Thanks a lot for your help!
for the input_calibration= statement
input_calibration = 15.497, 12.537, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40

I totally no idea what those number for?

**Comment by AlexeyAB** [comment]
> Also try to use OPENMP=1 SSE=1 or OPENMP=1 AVX=1
> --Wow, it works!
> OPENMP=1 SSE=1 CPU+ INT 8 inference: 492 faces, 0.106 s
> OPENMP=1 AVX=1 CPU+ INT 8 inference: 492 faces, 0.106 s

So it seems there is bug in code without SSE/AVX. I will fix it when I have time.

----

> input_calibration = 15.497, 12.537, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40
> 
> I totally no idea what those number for?

There is a simple explanation about `input_calibration`: https://github.com/AlexeyAB/darknet/issues/726#issuecomment-430593728

**Comment by Yinling-123** [comment]
My bad, I just double checked the Makefile, and found I mistakenly left GPU=1 when using OPENMP=1 SSE=1 or OPENMP=1 AVX=1, 

To clarify, what I tried so far for different CPU parameters in Makefile:
GPU=1  OPENMP=0   AVX=0  SSE=0 INT8 inference:  492 faces, 0.112s
GPU=0  OPENMP=0   AVX=0  SSE=0 INT8 inference:  2 faces, 32.611s
GPU=0  OPENMP=1   AVX=1  SSE=0 INT8 inference:  2 faces, 62.810s
GPU=0  OPENMP=1   AVX=0  SSE=1 INT8 inference:  2 faces, 98.009s
GPU=0  OPENMP=1   AVX=1  SSE=1 INT8 inference:  2 faces, 61.164s.

so there is no bug in code without SSE/AVX,  all CPU with different parameters with INT 8 inference detected 2 faces.

**Comment by Yinling-123** [comment]
and I compared map for the GPU version use thresh 0.15 with and without -quantized

without -quantized, the map is 0.763:
detections_count = 744642, unique_truth_count = 194506  
class_id = 0, name = face, 44642 ap = 76.35 % 
 for thresh = 0.15, precision = 0.76, recall = 0.76, F1-score = 0.76 
 for thresh = 0.15, TP = 148201, FP = 47238, FN = 46305, average IoU = 56.60 % 
 mean average precision (mAP) = 0.763532, or 76.35 % 
Total Detection Time: 3087.000000 Seconds

with quantized, map is 0.705, that is a 5.85% drop, with 1.2 times faster

> ./darknet detector map obj.data obj.cfg face.backup -thresh 0.15 -quantized
> 
> detections_count = 808240, unique_truth_count = 194506
> class_id = 0, name = face, 08240 ap = 70.47 %
> for thresh = 0.15, precision = 0.79, recall = 0.66, F1-score = 0.72
> for thresh = 0.15, TP = 129314, FP = 34161, FN = 65192, average IoU = 59.00 %
> mean average precision (mAP) = 0.704719, or 70.47 %
> Total Detection Time: 2603.000000 Seconds

**Comment by Yinling-123** [comment]
> If you have input_calibration = parameter in your cfg-file, then you can't get this warning Warning: input_calibration= in the cfg-file has less values 0 than convolutional layers 0. Do you still get this warning?
No, the warning disappeared with input_calibration = parameter
> What mAP can you get on CPU with -quantized?
I have run this on CPU for 3 hours now, only ~200 images were checked. I won't able to finish this mAP within 10 days... Actually, what I want is only to use CPU do the INT8 inference.

**Comment by AlexeyAB** [comment]
> `GPU=0 OPENMP=1 AVX=1 SSE=0` INT8 inference: 2 faces, 62.810s

Just try to set lower `-thresh 0.15` or `-thresh 0.1` at the end of command.

**Comment by Yinling-123** [comment]
> Just try to set lower -thresh 0.15 or -thresh 0.1 at the end of command.
Thanks for your suggestion! I tried different threshold, 
-thresh 0.02: detected 2 faces
-thresh 0.01:  detected 4 faces
-thresh 0.005: detected 11 faces
-thresh 0.001: detected 30 faces
I attached 0.001 result pic here. I read some thread before, someone also has the similar situation, the yolo2_light with low detection confidence score that you need to set a smaller threshold when doing the INT 8 inference. since the GPU inference doing good, I will be going to check the source code then.

![0 001](https://user-images.githubusercontent.com/26073213/47448468-f1efc180-d774-11e8-99d4-84024a043d85.png)

**Comment by AlexeyAB** [comment]
@Yinling-123 

1. Comment this line: https://github.com/AlexeyAB/yolo2_light/blob/f78f261c339eb1ed535dd9fe60a45ece68876701/src/yolov2_forward_network_quantized.c#L588

and un-comment this line: https://github.com/AlexeyAB/yolo2_light/blob/f78f261c339eb1ed535dd9fe60a45ece68876701/src/yolov2_forward_network_quantized.c#L589

And compile with `GPU=0 SSE=0 AVX=1 OPENMP=1`

----

2. Also you can try to use another slow way - comment this line: https://github.com/AlexeyAB/yolo2_light/blob/f78f261c339eb1ed535dd9fe60a45ece68876701/src/yolov2_forward_network_quantized.c#L588

and 
* un-comment this line: https://github.com/AlexeyAB/yolo2_light/blob/f78f261c339eb1ed535dd9fe60a45ece68876701/src/yolov2_forward_network_quantized.c#L590
* change `int16_t` to `int32_t` here: https://github.com/AlexeyAB/yolo2_light/blob/f78f261c339eb1ed535dd9fe60a45ece68876701/src/yolov2_forward_network_quantized.c#L548

* and compile with `GPU=0 SSE=0 AVX=0 OPENMP=1`

**Comment by Yinling-123** [comment]
> Comment this line:
> yolo2_light/src/yolov2_forward_network_quantized.c
> 
> Line 588 in f78f261
> 
>  gemm_nn_int8_int16(1, n, k, 1, a + t*k, k, b, n, c + t*n, n); 
> and un-comment this line:
> 
> yolo2_light/src/yolov2_forward_network_quantized.c
> 
> Line 589 in f78f261
> 
>  //gemm_nn_int8_int16_conv16(1, n, k, 1, a + t*k, k, b, n, c + t*n, n); 
> And compile with GPU=0 SSE=0 AVX=1 OPENMP=1

yes, I tried and still only detected 10 faces using threshold 0.24 which much less than 492 on GPU.
