### ISSUE TITLE
Status of OpenCL support

### ISSUE THREAD

**Issue by r0l1** [AlexeyAB/yolo2_light#4]
Does the OpenCL backend work? I would like to give it a try and help documenting this feature.

**Comment by AlexeyAB** [comment]
No. It isn't well tested. It works only for Yolo v2 (full / tiny) on Windows only, but not for Yolo v3.

**Comment by r0l1** [comment]
Ok. Good to know. I'll leave this [link](https://github.com/sowson/darknet) as a good OpenCL reference for Yolo networks. It worked quite well for me...
