### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by AleBasso80** [AlexeyAB/yolo2_light#58]
OS: Linux 16.04

Hello, 
while running the demo I noticed that the process memory keeps on increasing. 
Has anyone noticed the same issue?

Thanks
Alessandro

**Comment by isgursoy** [comment]
I have that leak in case of int8 while running multiple darknets in parallel. It is fine if I disable quantization.
@AlexeyAB is there any reason for that by design?

**Comment by isgursoy** [comment]
No it is not fixed.

**Comment by AleBasso80** [comment]
I solved by explicitly freeing prob and mask of each element of detections.
