### ISSUE TITLE
Why there is no input calibration command in darknet 

### ISSUE THREAD

**Issue by aluds123** [AlexeyAB/yolo2_light#65]
Dear @AlexeyAB ,
I insert the following command in order to obtain the input calibration parameters of our model, but it shows There isn't such command: calibration.
Can you help me to fix the problem?
![11](https://user-images.githubusercontent.com/43241182/61781442-ed0c8b00-ae36-11e9-9c95-2b4cf523c50b.png)

**Comment by alenweiru** [comment]
@aluds123 I have the same issue about no `calibrate command` .did you solve it?

**Comment by alenweiru** [comment]
I found that Windows command different from Linux form [here](https://github.com/AlexeyAB/darknet/issues/726#issuecomment-410179207)
