### ISSUE TITLE
how to implement FP16 version of this repo?

### ISSUE THREAD

**Issue by passion3394** [AlexeyAB/yolo2_light#67]
@AlexeyAB thanks for your great work, because my GPU is 2080ti, I want to use the FP16 quantization and test the inference time of it. What should I do to implement the FP16?

**Comment by passion3394** [comment]
found the solution.

**Comment by AleBasso80** [comment]
Hello passion3394,
do you have hint about how to achieve this goal? Did you notice a valuable latency improvement with the FP16 network?

Thanks!

**Comment by passion3394** [comment]
@AleBasso80 Yes, firstly, your GPU must support FP16, then use this repo to run yolo. On my datasets and 2080ti GPU, the inference time dropped from 75ms to 50ms.

**Comment by AleBasso80** [comment]
@passion3394 do you mean that I don't have to modify any compilation setting or config parameter? Does the network automatically choose fp16 if this is supported?

**Comment by passion3394** [comment]
@AleBasso80 Yes.

**Comment by AleBasso80** [comment]
@passion3394 . Thanks!
Just one more question: I'm comparing the results of this repo with the standard yolo v2. I noticed that this one works better with lying or crawling people. I compared the networks (I'm not using the int8 quantization) and I found that they differ in the reorg layer and in the yolov2_fuse_conv_batchnorm(network net). It does not seem to me that the former can cause a significant difference, therefore I'm concentrating on the layer fusion. Do you think this is the right path?

Cheers

**Comment by passion3394** [comment]
@AleBasso80 Why not use the method of Ablation Study?

**Comment by AleBasso80** [comment]
@passion3394 : good advice. I'll do it, thanks!
